/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Saul
 */
public class VistaCommand extends javax.swing.JFrame {

    /**
     * Creates new form VistaCommand
     */
    public VistaCommand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btncrear = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtnumcuenta = new javax.swing.JTextField();
        txtmonto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSaldo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("COMMAND");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel2.setText("Ingrese el numero de cuenta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel3.setText("Ingrese el monto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        btncrear.setText("Ingresar");
        jPanel1.add(btncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        btnVolver.setText("Volver");
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));
        jPanel1.add(txtnumcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, -1));
        jPanel1.add(txtmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        txtSaldo.setEditable(false);
        txtSaldo.setColumns(20);
        txtSaldo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSaldo.setLineWrap(true);
        txtSaldo.setRows(5);
        txtSaldo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtSaldo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtncrear() {
        return btncrear;
    }

    public void setBtncrear(JButton btncrear) {
        this.btncrear = btncrear;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }

    public JTextArea getTxtSaldo() {
        return txtSaldo;
    }

    public void setTxtSaldo(JTextArea txtSaldo) {
        this.txtSaldo = txtSaldo;
    }

    public JTextField getTxtmonto() {
        return txtmonto;
    }

    public void setTxtmonto(JTextField txtmonto) {
        this.txtmonto = txtmonto;
    }

    public JTextField getTxtnumcuenta() {
        return txtnumcuenta;
    }

    public void setTxtnumcuenta(JTextField txtnumcuenta) {
        this.txtnumcuenta = txtnumcuenta;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btncrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtSaldo;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtnumcuenta;
    // End of variables declaration//GEN-END:variables
}
