/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author Saul
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVisitor = new javax.swing.JButton();
        btnCommand = new javax.swing.JButton();
        btnMediator = new javax.swing.JButton();
        btnObserver = new javax.swing.JButton();
        btnStrategy = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patrones de comportamiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnVisitor.setBackground(new java.awt.Color(0, 153, 255));
        btnVisitor.setText("Visitor");
        jPanel1.add(btnVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 108, 95));

        btnCommand.setBackground(new java.awt.Color(204, 0, 255));
        btnCommand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCommand.setForeground(new java.awt.Color(255, 255, 255));
        btnCommand.setText("Command");
        jPanel1.add(btnCommand, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 108, 95));

        btnMediator.setBackground(new java.awt.Color(0, 51, 204));
        btnMediator.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMediator.setForeground(new java.awt.Color(255, 255, 255));
        btnMediator.setText("Mediator");
        jPanel1.add(btnMediator, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 108, 95));

        btnObserver.setBackground(new java.awt.Color(102, 0, 255));
        btnObserver.setForeground(new java.awt.Color(255, 255, 255));
        btnObserver.setText("Observer");
        jPanel1.add(btnObserver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 108, 95));

        btnStrategy.setBackground(new java.awt.Color(255, 51, 204));
        btnStrategy.setText("Strategy");
        jPanel1.add(btnStrategy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 108, 95));

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        Fondo.setText("jLabel2");
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 415));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCommand() {
        return btnCommand;
    }

    public void setBtnCommand(JButton btnCommand) {
        this.btnCommand = btnCommand;
    }

    public JButton getBtnMediator() {
        return btnMediator;
    }

    public void setBtnMediator(JButton btnMediator) {
        this.btnMediator = btnMediator;
    }

    public JButton getBtnObserver() {
        return btnObserver;
    }

    public void setBtnObserver(JButton btnObserver) {
        this.btnObserver = btnObserver;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JButton getBtnStrategy() {
        return btnStrategy;
    }

    public void setBtnStrategy(JButton btnStrategy) {
        this.btnStrategy = btnStrategy;
    }

    public JButton getBtnVisitor() {
        return btnVisitor;
    }

    public void setBtnVisitor(JButton btnVisitor) {
        this.btnVisitor = btnVisitor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCommand;
    private javax.swing.JButton btnMediator;
    private javax.swing.JButton btnObserver;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnStrategy;
    private javax.swing.JButton btnVisitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
