/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author Saul
 */
public class VistaCommand1 extends javax.swing.JFrame {

    /**
     * Creates new form VistaCommand1
     */
    public VistaCommand1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEcuador = new javax.swing.JButton();
        btnapEc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPeru = new javax.swing.JButton();
        btnapPer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ecuador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        btnEcuador.setText("Prender");
        jPanel1.add(btnEcuador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        btnapEc.setText("Apagar");
        jPanel1.add(btnapEc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ecuador.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 56, -1));

        jLabel3.setText("Peru");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        btnPeru.setText("Prender");
        jPanel1.add(btnPeru, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        btnapPer.setText("Apagar");
        jPanel1.add(btnapPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/peru.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 56, -1));

        btnReset.setText("Reset");
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public JButton getBtnEcuador() {
        return btnEcuador;
    }

    public void setBtnEcuador(JButton btnEcuador) {
        this.btnEcuador = btnEcuador;
    }

    public JButton getBtnPeru() {
        return btnPeru;
    }

    public void setBtnPeru(JButton btnPeru) {
        this.btnPeru = btnPeru;
    }

    public JButton getBtnapEc() {
        return btnapEc;
    }

    public void setBtnapEc(JButton btnapEc) {
        this.btnapEc = btnapEc;
    }

    public JButton getBtnapPer() {
        return btnapPer;
    }

    public void setBtnapPer(JButton btnapPer) {
        this.btnapPer = btnapPer;
    }

    public JButton getBtnReset() {
        return btnReset;
    }

    public void setBtnReset(JButton btnReset) {
        this.btnReset = btnReset;
    }
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEcuador;
    private javax.swing.JButton btnPeru;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnapEc;
    private javax.swing.JButton btnapPer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
